Repository juspay/hyperswitch-web, pull requests merged in 2024-11, with the labels that each got.

#757 fix: format function refactor for better logs readability
  src/Utilities/Utils.res
Labels: Ready for Review

#763 refactor: fetch api changes
  src/Utilities/Utils.res
Labels: Ready for Review

#738 feat: paze integration
  public/icons/orca.svg
  src/App.res
  src/Components/Spinner.res
  src/PaymentMethodCollectElement.res
  src/Payments/PaymentRequestButtonElement.res
  src/Payments/PazeButton.res
  src/Payments/PazeTypes.res
  src/Payments/PazeWallet.res
  src/Types/SessionsType.res
  src/Utilities/PaymentBody.res
  src/Utilities/PaymentHelpers.res
  src/orca-loader/Elements.res
Labels: Ready for Review

#759 fix: card input error text correction
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/Payment.res
  src/Payments/CardPayment.res
Labels: Ready for Review

#607 refactor: variant to str mapper refactor
  src/Types/CardThemeType.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#770 refactor: orcalogger to hyperlogger for better name
  .github/CODEOWNERS
  src/App.res
  src/Payments/PaypalSDKHelpers.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/PreMountLoader.res
  src/ThreeDSAuth.res
  src/ThreeDSMethod.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/ErrorUtils.res
  src/Utilities/LoggerUtils.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/PmAuthConnectorUtils.res
  src/Utilities/RecoilAtoms.res
  src/Utilities/Utils.res
  src/hyper-loader/Elements.res
  src/hyper-loader/Hyper.res
  src/hyper-loader/HyperLoader.res
  src/hyper-loader/LoaderPaymentElement.res
  src/hyper-loader/PaymentMethodsManagementElements.res
  src/hyper-loader/PaymentSession.res
  src/hyper-loader/PaymentSessionMethods.res
  src/hyper-loader/Types.res
  src/hyper-log-catcher/ErrorBoundary.res
  src/hyper-log-catcher/HyperLogger.res
  src/hyper-log-catcher/ReusableReactSuspense.res
  src/hyper-log-catcher/Sentry.res
  src/libraries/Recoil.res
  webpack.common.js
Labels: Enhancement / Refactoring, Ready for Review

#583 refactor: refactor PreMountLoader
  src/Payments/PreMountLoader.res
  src/Utilities/Utils.res
Labels: Enhancement / Refactoring, Ready for Review

#776 feat: add dynamic fields support for affirm
  src/Payments/PaymentMethodsRecord.res
Labels: Ready for Review

#765 refactor: minor refactoring
  src/Hooks/Fetcher.res
  src/PaymentMethodCollectElement.res
  src/Payments/PaypalSDKHelpers.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/PaymentHelpersTypes.res
  src/Utilities/URLModule.res
  src/Utilities/Utils.res
  src/Window.res
Labels: Enhancement / Refactoring, Ready for Review

#775 feat: added dynamic fields support for sepa bank transfer
  src/Payments/SepaBankTransfer.res
  src/Utilities/PaymentBody.res
Labels: Ready for Review

#769 refactor: premount loader - 2
  src/Payments/PreMountLoader.res
Labels: Enhancement / Refactoring, Ready for Review

#764 test: added nested iframe test support in cypress and external 3ds ne…
  cypress-tests/cypress/e2e/external-3DS-netcetera-e2e-test.cy.ts
  cypress-tests/cypress/support/commands.ts
  cypress-tests/cypress/support/types.ts
  cypress-tests/cypress/support/utils.ts
Labels: Ready for Review, TypeScript, Testing

#777 chore: added dynamic fields for ach
  src/Payments/ACHBankTransfer.res
  src/Payments/PaymentMethodsRecord.res
  src/Utilities/PaymentBody.res
Labels: Ready for Review

#721 test: added test cases in cypress
  cypress-tests/cypress/e2e/saved-card-flow-e2e-test.cy.ts
  cypress-tests/cypress/e2e/stripe-3DS-card-flow-e2e-test.cy.ts
  cypress-tests/cypress/e2e/stripe-manual-capture-card-flow-e2e-test.cy.ts
  cypress-tests/cypress/e2e/stripe-no-3DS-card-flow-e2e-test.cy.ts
  cypress-tests/cypress/support/cards.ts
  cypress-tests/cypress/support/commands.ts
  cypress-tests/cypress/support/types.ts
Labels: Testing

#780 chore: added dynamic fields support for bacs bank transfer
  src/Payments/BacsBankTransfer.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/PaymentBody.res
  src/Utilities/Utils.res
Labels: Enhancement / Refactoring, Ready for Review

#782 chore: add dynamic fields support for walley
  src/Utilities/DynamicFieldsUtils.res
Labels: Ready for Review

#783 chore: enabled dynamic fields for pay bright
  src/Utilities/DynamicFieldsUtils.res
Labels: Enhancement / Refactoring, Ready for Review

#784 chore: enabled dynamic fields for multibanco bank transfer
  src/Payments/PaymentMethodsRecord.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/PaymentBody.res
Labels: Enhancement / Refactoring, Ready for Review

#768 refactor: async await refactoring - 1
  src/Components/SavedMethodItem.res
  src/Components/SavedPaymentManagement.res
  src/Payments/PazeButton.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/QRCodeDisplay.res
  src/Utilities/PaymentUtils.res
Labels: Enhancement / Refactoring, Ready for Review

#771 refactor: replace if statements with switch in cardError code
  src/CardUtils.res
  src/Payment.res
Labels: Enhancement / Refactoring, Ready for Review

#779 feat: express checkout for paze
  src/CardUtils.res
  src/LoaderController.res
  src/Payments/PaymentRequestButtonElement.res
  src/Payments/PazeButton.res
  src/Payments/PazeWallet.res
  src/RenderPaymentMethods.res
  src/Types/ApplePayTypes.res
  src/Types/CardThemeType.res
  src/Types/PaymentType.res
  src/Utilities/Utils.res
  src/hyper-loader/Elements.res
Labels: Ready for Review

#789 fix: paze express checkout for multiple iframe
  src/Utilities/Utils.res
  src/hyper-loader/Elements.res
Labels: Ready for Review

#793 refactor: changed cvc to security code
  src/Components/SavedCardItem.res
  src/LocaleStrings/ChineseLocale.res
Labels: Ready for Review

#794 fix: card holder name
  src/Components/DynamicFields.res
Labels: Ready for Review

#795 style: minor ui styling
  src/Components/DynamicFields.res
  src/Payments/BankDebitModal.res
  src/Payments/CardPayment.res
Labels: Ready for Review

#798 refactor: stringify json for block confirm body and headers
  src/Utilities/PaymentHelpers.res
Labels: Ready for Review

#799 chore: added validations for card holder name
  src/Components/FullNamePaymentInput.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/Utilities/DynamicFieldsUtils.res
Labels: Ready for Review

#800 chore: added validations for nick name field
  src/Components/NicknamePaymentInput.res
  src/Payments/CardPayment.res
  src/Utilities/RecoilAtoms.res
  src/Utilities/Utils.res
Labels: Ready for Review

#801 chore: added suport for adding email address in paze
  src/Payments/PazeTypes.res
  src/Payments/PazeWallet.res
Labels: Ready for Review

#802 chore: sent a post message for expiry date
  src/Payments/CardPayment.res
Labels: Ready for Review

#803 chore: removed console logs
  src/Payments/PazeWallet.res
Labels: Ready for Review

#792 feat: added paypal tabs flow support for billing details
  src/PaymentElement.res
  src/Payments/PayPal.res
  src/Payments/PayPal.resi
  src/Payments/PayPalHelpers.res
  src/Payments/PaymentMethodsRecord.res
  src/Payments/PaymentRequestButtonElement.res
  src/Types/PaymentModeType.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/PaymentUtils.res
Labels: Ready for Review

#810 fix: crypto currency payment method
  src/Payments/PaymentMethodsWrapper.res
  src/Utilities/DynamicFieldsUtils.res
Labels: Ready for Review

#806 feat: samsung pay added
  src/CardUtils.res
  src/Components/SurchargeUtils.res
  src/LoaderController.res
  src/Payments/GPay.res
  src/Payments/KlarnaSDK.res
  src/Payments/PayPal.res
  src/Payments/PaymentRequestButtonElement.res
  src/Payments/PaypalSDK.res
  src/Payments/SamsungPayComponent.res
  src/RenderPaymentMethods.res
  src/Types/CardThemeType.res
  src/Types/PaymentModeType.res
  src/Types/PaymentType.res
  src/Types/SamsungPayType.res
  src/Types/SessionsType.res
  src/Utilities/PaymentBody.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/PaymentHelpersTypes.res
  src/Utilities/PaymentUtils.res
  src/Utilities/RecoilAtoms.res
  src/Utilities/SamsungPayHelpers.res
  src/Utilities/Utils.res
  src/hyper-loader/Elements.res
  src/hyper-loader/Hyper.res
Labels: Ready for Review
