Repository juspay/hyperswitch-web, pull requests merged in 2024-07, with the labels that each got.

#453 fix: manual retries
  src/Components/SavedMethods.res
  src/Payment.res
  src/Payments/ACHBankDebit.res
  src/Payments/ACHBankTransfer.res
  src/Payments/ApplePay.res
  src/Payments/BacsBankDebit.res
  src/Payments/BacsBankTransfer.res
  src/Payments/BecsBankDebit.res
  src/Payments/Boleto.res
  src/Payments/CardPayment.res
  src/Payments/GPay.res
  src/Payments/KlarnaPayment.res
  src/Payments/KlarnaSDK.res
  src/Payments/PayPal.res
  src/Payments/PaymentMethodsWrapper.res
  src/Payments/PaypalSDK.res
  src/Payments/PaypalSDKHelpers.res
  src/Payments/SepaBankDebit.res
  src/Payments/SepaBankTransfer.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/PaymentHelpers.res
Labels: Ready for Review

#469 fix: wallets on top for saved cards flow
  src/Utilities/PaymentUtils.res
Labels: Ready for Review

#461 feat: pm auth connector integration - Plaid
  src/App.res
  src/Components/SavedCardItem.res
  src/Components/SavedMethods.res
  src/LoaderController.res
  src/Payments/ACHBankDebit.res
  src/Payments/AddBankDetails.res
  src/Payments/PaymentMethodsRecord.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/SepaBankDebit.res
  src/Types/PaymentType.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/PmAuthConnectorUtils.res
  src/Utilities/Utils.res
  src/libraries/Plaid.res
  src/orca-loader/Elements.res
  src/orca-loader/Hyper.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#471 fix: info element added & logs addition
  src/LoaderController.res
  src/Payments/AddBankDetails.res
  src/Payments/BacsBankDebit.res
  src/Payments/PlaidSDKIframe.res
  src/Utilities/PaymentHelpers.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#467 fix: payment data filled event logs for few payment methods
  src/Payments/KlarnaSDK.res
  src/Payments/PayPal.res
  src/Payments/PaypalSDK.res
  src/Payments/PaypalSDKHelpers.res
Labels: Ready for Review

#474 fix: integ api change
  webpack.common.js
  webpack.dev.js
Labels: Ready for Review

#476 fix: passing customer acceptance if recurring_enabled is false in saved methods list
  src/Components/SavedMethods.res
  src/Types/PaymentType.res
  src/orca-loader/PaymentSessionMethods.res
Labels: Ready for Review

#392 feat: payment-management added
  public/icons/orca.svg
  src/App.res
  src/CardTheme.res
  src/CardUtils.res
  src/Components/PaymentElementShimmer.res
  src/Components/SavedMethodItem.res
  src/Components/SavedMethods.res
  src/Components/SavedPaymentManagement.res
  src/Hooks/CommonHooks.res
  src/LoaderController.res
  src/PaymentManagement.res
  src/PaymentManagementLazy.res
  src/Payments/PreMountLoader.res
  src/RenderPaymentMethods.res
  src/Types/CardThemeType.res
  src/Types/PaymentType.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/Utils.res
  src/orca-loader/Elements.res
  src/orca-loader/Hyper.res
  src/orca-loader/LoaderPaymentElement.res
  src/orca-loader/PaymentMethodsManagementElements.res
  src/orca-loader/PaymentSession.res
  src/orca-loader/PaymentSessionMethods.res
  src/orca-loader/Types.res
  src/orca-log-catcher/ErrorBoundary.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#480 fix: date of birth validations
  src/Payments/DateOfBirth.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/RecoilAtoms.res
  src/Utilities/Utils.res
  src/libraries/DatePicker.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#491 feat: added upi collect payment method type
  public/icons/orca.svg
  src/Components/DynamicFields.res
  src/Components/VpaIdPaymentInput.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/Payments/PaymentMethodsRecord.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/RecoilAtoms.res
  src/Utilities/Utils.res
Labels: Ready for Review

#492 fix: premount loader fix
  src/Payments/PreMountLoader.res
Labels: Ready for Review

#493 chore: remove pragma marks from file that not needed
  src/LoaderController.res
  src/orca-loader/LoaderPaymentElement.res
Labels: Ready for Review

#498 fix: error string
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/Payments/DateOfBirth.res
Labels: Ready for Review

#460 feat(payout-link): add input validations for payment methods in CollectWidget
  public/icons/orca.svg
  src/App.res
  src/CollectWidget.res
  src/Components/InputField.res
  src/PaymentMethodCollectElement.res
  src/PaymentMethodCollectElementLazy.res
  src/Types/PaymentMethodCollectTypes.res
  src/Utilities/PaymentMethodCollectUtils.res
Labels: Ready for Review

#502 feat: language preference for mifinity added
  src/App.res
  src/CardTheme.res
  src/Components/DynamicFields.res
  src/LoaderController.res
  src/Payments/CardPayment.res
  src/Payments/PaymentMethodsRecord.res
  src/Types/CardThemeType.res
  src/Utilities/DynamicFieldsUtils.res
  src/Window.res
Labels: Ready for Review

#503 refactor: moving declarations in window into a sub-module
  src/CardTheme.res
  src/Hooks/Fetcher.res
  src/LoaderController.res
  src/Utilities/PaymentBody.res
  src/Window.res
  src/orca-loader/Hyper.res
  src/orca-log-catcher/ErrorBoundary.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Enhancement / Refactoring, Ready for Review

#505 fix(payout): handle tab order updates
  src/CollectWidget.res
Labels: Ready for Review

#504 feat: passing X-Merchant-Domain in the headers for Sessions Call
  src/App.res
  src/Payments/PreMountLoader.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/Utils.res
  src/orca-loader/Elements.res
Labels: Ready for Review

#516 fix: customer acceptance issue for bank debits
  src/Payments/ACHBankDebit.res
  src/Utilities/PaymentBody.res
Labels: Ready for Review

#527 feat: pix-ItauBank api contract changes
  src/Components/DynamicFields.res
  src/Components/PixPaymentInput.res
  src/Payments/PaymentMethodsRecord.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/RecoilAtoms.res
Labels: Ready for Review

#528 fix: pix confirm call and added locale support
  src/CardTheme.res
  src/Components/PixPaymentInput.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringHelper.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
Labels: Ready for Review

#523 docs(readme): increase Readme Specificity
  README.md
Labels: Ready for Review

#520 feat(payout): add localisation for payout widget
  src/CardTheme.res
  src/CollectWidget.res
  src/LoaderController.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/ConstantStrings.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/PaymentMethodCollectElement.res
  src/Utilities/PaymentMethodCollectUtils.res
Labels: Ready for Review, payout, i18n

#529 feat: added support for collecting_billing_details_from_wallets
  src/PaymentElement.res
  src/Payments/ApplePay.res
  src/Payments/ApplePay.resi
  src/Payments/GPay.res
  src/Payments/GPay.resi
  src/Payments/PaymentMethodsRecord.res
  src/Payments/PaymentRequestButtonElement.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/PaymentUtils.res
Labels: Ready for Review
