Repository juspay/hyperswitch-web, pull requests merged in 2024-08, with the labels that each got.

#532 fix: removal of unnecessary package
  package-lock.json
  package.json
Labels: Ready for Review

#535 refactor(payout): remove error code and error message from status page
  src/PaymentMethodCollectElement.res
Labels: payout

#534 fix: package removal
  Hyperswitch-React-Demo-App/package.json
  README.md
  package-lock.json
  package.json
  rescript.json
  src/Components/KountSDK.res
Labels: Ready for Review

#536 fix: webpack upgraded to new version for removing vulnerability
  Hyperswitch-React-Demo-App/package.json
  Hyperswitch-React-Demo-App/webpack.dev.js
  package-lock.json
  package.json
  webpack.dev.js
Labels: Ready for Review

#538 fix: semantic package update
  package-lock.json
  package.json
  webpack.common.js
Labels: Ready for Review

#542 fix: parse exn error handle
  src/Components/AddressPaymentInput.res
  src/Components/BillingNamePaymentInput.res
  src/Components/BlikCodePaymentInput.res
  src/Components/EmailPaymentInput.res
  src/Components/FullNamePaymentInput.res
  src/Components/FullScreenPortal.res
  src/Components/PaymentLoader.res
  src/Components/PixPaymentInput.res
  src/Components/SavedMethods.res
  src/Components/VpaIdPaymentInput.res
  src/LoaderController.res
  src/Payment.res
  src/PaymentElement.res
  src/Payments/ACHBankDebit.res
  src/Payments/ACHBankTransfer.res
  src/Payments/AddBankDetails.res
  src/Payments/BacsBankDebit.res
  src/Payments/BacsBankTransfer.res
  src/Payments/BankTransfersPopup.res
  src/Payments/BecsBankDebit.res
  src/Payments/Boleto.res
  src/Payments/CardPayment.res
  src/Payments/DateOfBirth.res
  src/Payments/GPay.res
  src/Payments/KlarnaPayment.res
  src/Payments/PaymentMethodsWrapper.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/PreMountLoader.res
  src/Payments/QRCodeDisplay.res
  src/Payments/SepaBankDebit.res
  src/Payments/SepaBankTransfer.res
  src/Payments/VoucherDisplay.res
  src/ThreeDSAuth.res
  src/ThreeDSMethod.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/PaymentHelpers.res
Labels: Ready for Review

#544 refactor: unit removed
  src/App.res
  src/CardUtils.res
  src/Components/DropdownField.res
  src/Components/DynamicFields.res
  src/Components/Input.res
  src/Components/InputField.res
  src/Components/PaymentDropDownField.res
  src/Components/PaymentField.res
  src/Components/PaymentInputField.res
  src/Components/SavedMethods.res
  src/Components/SavedPaymentManagement.res
  src/Hooks/OutsideClick.res
  src/LoaderController.res
  src/Payment.res
  src/PaymentElement.res
  src/Payments/ACHBankDebit.res
  src/Payments/ACHBankTransfer.res
  src/Payments/ApplePay.res
  src/Payments/BacsBankDebit.res
  src/Payments/BacsBankTransfer.res
  src/Payments/BecsBankDebit.res
  src/Payments/Boleto.res
  src/Payments/CardPayment.res
  src/Payments/GPay.res
  src/Payments/KlarnaPayment.res
  src/Payments/KlarnaSDK.res
  src/Payments/PayPal.res
  src/Payments/PaymentMethodsRecord.res
  src/Payments/PaymentMethodsWrapper.res
  src/Payments/PaypalSDK.res
  src/Payments/PaypalSDKHelpers.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/PreMountLoader.res
  src/Payments/SepaBankDebit.res
  src/Payments/SepaBankTransfer.res
  src/Payments/VoucherDisplay.res
  src/ThreeDSAuth.res
  src/ThreeDSMethod.res
  src/Utilities/ApiEndpoint.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/ErrorUtils.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/LoggerUtils.res
  src/Utilities/PaymentBody.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/PmAuthConnectorUtils.res
  src/Utilities/Utils.res
  src/orca-loader/Elements.res
  src/orca-loader/Hyper.res
  src/orca-loader/HyperLoader.res
  src/orca-loader/PaymentMethodsManagementElements.res
  src/orca-loader/PaymentSession.res
  src/orca-loader/PaymentSessionMethods.res
  src/orca-log-catcher/OrcaLogger.res
Labels: Ready for Review

#543 feat: sdk pay now button enable prop added
  src/Components/PayNowButton.res
  src/Hooks/UtilityHooks.res
  src/TabCard.res
  src/Types/PaymentType.res
  src/Utilities/Utils.res
  src/orca-loader/Elements.res
  src/orca-loader/Hyper.res
  src/orca-loader/LoaderPaymentElement.res
Labels: Ready for Review

#546 fix: fixed structure of billing details in payment body
  src/Payments/PaymentMethodsRecord.res
  src/Utilities/DynamicFieldsUtils.res
  src/Utilities/PaymentBody.res
  src/Utilities/Utils.res
Labels: Ready for Review

#541 feat: open banking PIS integration
  src/Payments/PaymentMethodsRecord.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/QRCodeDisplay.res
  src/ThreeDSAuth.res
  src/Utilities/PaymentHelpers.res
  src/orca-loader/Elements.res
Labels: Ready for Review

#553 refactor: added classes for billing section and billing details text
  src/Components/DropdownField.res
  src/Components/DynamicFields.res
Labels: Ready for Review

#554 refactor: text change for sepa debit terms locale
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
Labels: Ready for Review

#555 feat: dockerize the hyperswitch-web
  Dockerfile
Labels: Ready for Review

#570 fix: google pay button border
  src/RenderPaymentMethods.res
Labels: Ready for Review, DO NOT MERGE

#567 refactor: sdk pay now always enabled
  src/Components/PayNowButton.res
  src/Hooks/UtilityHooks.res
  src/TabCard.res
  src/Types/PaymentType.res
  src/Utilities/RecoilAtoms.res
Labels: Ready for Review

#581 fix(payout): dropdown for selecting payment methods, UI updates
  src/CollectWidget.res
  src/PaymentMethodCollectElement.res
Labels: Ready for Review, payout

#582 chore: rename handlePostMessage to messageParentWindow
  rescript.json
  src/Components/AddBankAccount.res
  src/Components/AddressPaymentInput.res
  src/Components/FullScreenDivDriver.res
  src/Components/InputField.res
  src/Components/Modal.res
  src/Components/PayNowButton.res
  src/Components/PaymentLoader.res
  src/Components/SavedPaymentManagement.res
  src/LoaderController.res
  src/PaymentElement.res
  src/Payments/AddBankDetails.res
  src/Payments/BankTransfersPopup.res
  src/Payments/GPay.res
  src/Payments/KlarnaSDK.res
  src/Payments/KlarnaSDKTypes.res
  src/Payments/PaypalSDK.res
  src/Payments/PaypalSDKHelpers.res
  src/Payments/PlaidSDKIframe.res
  src/Payments/PreMountLoader.res
  src/Payments/QRCodeDisplay.res
  src/Payments/VoucherDisplay.res
  src/SingleLineCardPayment.res
  src/ThreeDSAuth.res
  src/ThreeDSMethod.res
  src/Types/GooglePayType.res
  src/Types/PaypalSDKTypes.res
  src/Types/PostalCodeType.res
  src/Types/ThemeImporter.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/GooglePayHelpers.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/Utils.res
  src/libraries/Promise.res
  src/orca-loader/Elements.res
  src/orca-loader/LoaderPaymentElement.res
  src/orca-loader/Types.res
  src/orca-log-catcher/ErrorBoundary.res
Labels: Ready for Review
