Repository juspay/hyperswitch-web, pull requests merged in 2025-05, with the labels that each got.

#1016 docs: add missing loaded scripts in security inventory docs
  docs/SCRIPT_INVENTORY.md
Labels: Ready for Review

#1019 fix: csp correction
  webpack.common.js
Labels: Ready for Review

#1018 feat: 3ds redirection inside popup
  src/App.res
  src/Payments/ThreeDSRedirectionModal.res
  src/Types/HyperLoggerTypes.res
  src/Types/PaymentConfirmTypes.res
  src/Utilities/PaymentHelpers.res
Labels: Ready for Review

#1021 test: mifinity payment flow
  cypress-tests/cypress/e2e/mifinity-flow-test.cy.ts
  cypress-tests/cypress/support/utils.ts
  src/Utilities/TestUtils.res
Labels: Ready for Review, Testing

#1022 test: crypto payment flow
  cypress-tests/cypress/e2e/crpto-flow-test.cy.ts
  cypress-tests/cypress/support/utils.ts
Labels: Ready for Review, Testing

#1023 fix: encrypted payload fixed
  src/Utilities/PaymentBody.res
Labels: Ready for Review

#1020 test(cypress): redsys 3ds flow test
  cypress-tests/cypress/e2e/redsys-3ds-flow-test.cy.ts
  cypress-tests/cypress/support/cards.ts
Labels: Ready for Review, Testing

#1015 fix: fullName and phoneNumber is required to add card with visa CTP
  src/Components/DynamicFields.res
  src/Types/ClickToPayHelpers.res
  src/Utilities/DynamicFieldsUtils.res
Labels: Ready for Review

#1024 chore: add environment in sentry
  src/hyper-log-catcher/Sentry.res
Labels: Ready for Review

#1026 chore: add css rule in payment method container
  src/RenderPaymentMethods.res
Labels: Closed

#1025 chore: add git submodule initialization to postinstall script
  package.json
Labels: Closed

#1028 chore: add csp for another klarna flow
  webpack.common.js
Labels: Ready for Review

#1027 chore: demo app v1-v2 changes
  .github/workflows/run-automation-test.yml
  Hyperswitch-React-Demo-App/.env
  Hyperswitch-React-Demo-App/package.json
  Hyperswitch-React-Demo-App/server.js
  Hyperswitch-React-Demo-App/webpack.common.js
Labels: Ready for Review

#1032 feat: added support for demo app v2
  Hyperswitch-React-Demo-App/server.js
  Hyperswitch-React-Demo-App/src/Payment.js
  Hyperswitch-React-Demo-App/src/utils.js
Labels: Ready for Review
