Repository juspay/hyperswitch-web, pull requests merged in 2025-02, with the labels that each got.

#840 fix: updated CVC and expiry behaviour
  src/Payment.res
Labels: Ready for Review

#878 chore: docker parallel issue for webpack and rescript
  Dockerfile
Labels: Ready for Review

#885 fix: improve web accessibility with better ARIA support and contrast fixes
  public/build.html
  public/fullscreenIndexTemplate.html
  src/CardUtils.res
  src/Components/AddBankAccount.res
  src/Components/DropdownField.res
  src/Components/Input.res
  src/Components/InputField.res
  src/Components/Or.res
  src/Components/PaymentDropDownField.res
  src/Components/PaymentField.res
  src/Components/PaymentInputField.res
  src/Components/PoweredBy.res
  src/Components/SaveDetailsCheckbox.res
  src/Components/SavedCardItem.res
  src/Components/SavedMethods.res
  src/PaymentElement.res
  src/Payments/PaymentRequestButtonElement.res
  src/Payments/QRCodeDisplay.res
  src/ThreeDSAuth.res
  src/ThreeDSMethod.res
  src/Window.res
  src/hyper-loader/Elements.res
  src/hyper-loader/LoaderPaymentElement.res
  src/hyper-loader/PaymentMethodsManagementElements.res
Labels: Ready for Review

#890 feat: emit payment method info
  src/Components/AccordionContainer.res
  src/Components/SavedCardItem.res
  src/PaymentElement.res
  src/PaymentOptions.res
  src/Payments/ApplePay.res
  src/Payments/GPay.res
  src/Payments/KlarnaSDK.res
  src/Payments/PayPal.res
  src/Payments/PaypalSDKHelpers.res
  src/Payments/PazeButton.res
  src/Payments/SamsungPayComponent.res
  src/Utilities/PaymentUtils.res
  src/hyper-log-catcher/HyperLogger.res
Labels: Ready for Review

#796 test: add automated Cypress test for card number input validation
  cypress-tests/cypress/e2e/card-number-validation-test.cy.ts
Labels: Ready for Review, Testing

#903 fix: ensure country code dropdown appears and prevent text overflow
  src/Components/DropdownField.res
  src/Components/PaymentField.res
Labels: Ready for Review

#825 test: test card payment with multiple card brands and card numbers
  cypress-tests/cypress/e2e/card-number-validation-test.cy.ts
  cypress-tests/cypress/support/cards.ts
Labels: Ready for Review, Testing

#843 test: add test case for removing cvc and expiry
  cypress-tests/cypress/e2e/cvc-checks-e2e-test.cy.ts
Labels: Ready for Review, Testing

#905 fix: remove unwanted gap in dynamic fields
  src/Components/DynamicFields.res
Labels: Ready for Review

#907 refactor: state.json file updated
  src/States.json
Labels: Ready for Review

#908 refactor: state.json file updated
  src/States.json
Labels: Ready for Review

#909 fix: shimmer fixed for saved flow
  src/Components/SavedMethods.res
Labels: Ready for Review

#912 chore(eslint): enforce no console logs in codebase
  .eslintrc.json
  src/PaymentMethodCollectElement.res
  src/Payments/BecsBankDebit.res
  src/Payments/PazeWallet.res
  src/Payments/QRCodeDisplay.res
  src/Types/ClickToPayHelpers.res
  src/Utilities/ApplePayHelpers.res
  src/Utilities/PaymentHelpers.res
  src/Utilities/Utils.res
  src/hyper-loader/Elements.res
  src/hyper-loader/Hyper.res
  src/hyper-loader/LoaderPaymentElement.res
  src/hyper-log-catcher/Sentry.res
Labels: Ready for Review

#913 fix: clear card expiry and CVC when switching to saved method and back
  src/Payment.res
Labels: Ready for Review

#915 refactor: formated main branch code
  src/BubblegumTheme.res
  src/FormViewJourney.res
  src/Hooks/CommonHooks.res
  src/Types/PaypalSDKTypes.res
  src/Types/SessionsType.res
  src/Utilities/PaymentBody.res
  src/hyper-loader/PaymentSessionMethods.res
Labels: Ready for Review

#917 fix: fixed shimmer stuck for click to pay
  src/Components/ClickToPayLearnMore.res
  src/Components/PaymentElementShimmer.res
  src/Components/SavedMethods.res
  src/PaymentElement.res
  src/Types/ClickToPayHelpers.res
Labels: Ready for Review

#874 feat: added display billing details feature
  src/Components/SavedCardItem.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/LocaleStringTypes.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/LocaleStrings/TraditionalChineseLocale.res
  src/Types/PaymentType.res
Labels: Ready for Review

#919 fix: fixed crypto pay body payload
  src/Utilities/PaymentBody.res
Labels: Ready for Review, Easy, hyperswitch-web, rescript

#918 chore: added bank names like maybank and citibank
  src/Bank.res
  src/LocaleStrings/ArabicLocale.res
  src/LocaleStrings/CatalanLocale.res
  src/LocaleStrings/ChineseLocale.res
  src/LocaleStrings/DeutschLocale.res
  src/LocaleStrings/DutchLocale.res
  src/LocaleStrings/EnglishGBLocale.res
  src/LocaleStrings/EnglishLocale.res
  src/LocaleStrings/FrenchBelgiumLocale.res
  src/LocaleStrings/FrenchLocale.res
  src/LocaleStrings/HebrewLocale.res
  src/LocaleStrings/ItalianLocale.res
  src/LocaleStrings/JapaneseLocale.res
  src/LocaleStrings/PolishLocale.res
  src/LocaleStrings/PortugueseLocale.res
  src/LocaleStrings/RussianLocale.res
  src/LocaleStrings/SpanishLocale.res
  src/LocaleStrings/SwedishLocale.res
  src/LocaleStrings/TraditionalChineseLocale.res
Labels: Ready for Review

#925 refactor: minor refactor
  src/App.res
Labels: Ready for Review
